In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the data
df = pd.read_csv('/Users/downy/Documents/2025 LG aimers/DKU-LG-Capstone-6/shared codes/data/train.csv')

In [72]:
interest_col = [
    '총 시술 횟수',
    "클리닉 내 총 시술 횟수",
    "IVF 시술 횟수",
    "DI 시술 횟수",
    "총 임신 횟수",
    "IVF 임신 횟수",
    "DI 임신 횟수",
    "총 출산 횟수",
    "IVF 출산 횟수",
    "DI 출산 횟수",
    "임신 성공 여부"
]

# df의 각 컬럼에 대해 valuecounts를 통해 각 값의 개수를 세어보자
# for col in interest_col:
#     print(df[col].value_counts())

    
# df = df[interest_col]

In [73]:
import pandas as pd

def preprocess_and_calculate_miscarriage(data):
    # 문자열에서 숫자만 추출 (예: "0회" → 0, "1회" → 1)
    def extract_number(value):
        if "이상" in value:
            return 6  # "6회 이상"은 6으로 처리
        return int(value.replace("회", ""))

    # 복사본 생성(본인이 불러온 dataset)
    df = data.copy()

    # 숫자 값으로 변환
    df['총 시술 횟수'] = df['총 시술 횟수'].apply(extract_number)
    df['총 임신 횟수'] = df['총 임신 횟수'].apply(extract_number)
    df['총 출산 횟수'] = df['총 출산 횟수'].apply(extract_number)

    # 유산 여부 계산
    df['유산 여부'] = df['총 임신 횟수'] > df['총 출산 횟수']
    # df['유산 횟수'] = df['총 임신 횟수'] - df['총 출산 횟수']

    # 불임 여부 계산
    df['불임 여부'] = df['총 시술 횟수'] > df['총 임신 횟수']
    # df['불임 횟수'] = df['총 시술 횟수'] - df['총 임신 횟수']


    return df

In [74]:
data = preprocess_and_calculate_miscarriage(df)
data

,ID,시술 시기 코드,시술 당시 나이,임신 시도 또는 마지막 임신 경과 연수,시술 유형,특정 시술 유형,배란 자극 여부,배란 유도 유형,단일 배아 이식 여부,착상 전 유전 검사 사용 여부,...,PGD 시술 여부,PGS 시술 여부,난자 채취 경과일,난자 해동 경과일,난자 혼합 경과일,배아 이식 경과일,배아 해동 경과일,임신 성공 여부,유산 여부,불임 여부
0,TRAIN_000000,TRZKPL,만18-34세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,3.0,NaN,0,False,False
1,TRAIN_000001,TRYBLT,만45-50세,NaN,IVF,ICSI,0,알 수 없음,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0,False,False
2,TRAIN_000002,TRVNRY,만18-34세,NaN,IVF,IVF,1,기록되지 않은 시행,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,2.0,NaN,0,False,True
3,TRAIN_000003,TRJXFG,만35-37세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0,False,True
4,TRAIN_000004,TRVNRY,만18-34세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,3.0,NaN,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256346,TRAIN_256346,TRYBLT,만18-34세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,5.0,NaN,0,False,True
256347,TRAIN_256347,TRYBLT,만38-39세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,3.0,NaN,1,False,True
256348,TRAIN_256348,TRVNRY,만35-37세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,3.0,NaN,0,False,True
256349,TRAIN_256349,TRZKPL,만38-39세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,...,NaN,NaN,0.0,NaN,0.0,1.0,NaN,1,False,True
256350,TRAIN_256350,TRXQMD,만35-37세,NaN,IVF,IVF,0,알 수 없음,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1,False,True

In [78]:
data = data[['유산 여부', '불임 여부', '임신 성공 여부']]
data.corr()

             유산 여부     불임 여부  임신 성공 여부
유산 여부     1.000000  0.117608 -0.005642
불임 여부     0.117608  1.000000 -0.063759
임신 성공 여부 -0.005642 -0.063759  1.000000